---
# handlers file for netzwirt.seafile

- name: restart seafile
  service:
    name: "{{ item }}"
    state: restarted
  ignore_errors: yes # init script returns non zero when allready running
  with_items:
  - seafile
  - seahub

