       
- name: mysql client config
  template:
    src: my.cnf.j2
    dest: "{{ seafile_home_path }}/.my.cnf"
    owner: "{{ seafile_user }}"
    group: "{{ seafile_group }}"
    mode: 0400
    

- name: create mysql databases (delegate mysql task)
  mysql_db: 
    name: "{{ item }}" 
    state: present
    encoding: utf8
  delegate_to: "{{ seafile_login_host }}"
  with_items: 
  - "{{ seafile_database_prefix }}ccnet"
  - "{{ seafile_database_prefix }}seafile"
  - "{{ seafile_database_prefix }}seahub" 
  register: __seafile_database_create
  when: seafile_create_database and seafile_delegate_to_login_host


- name: create mysql databases (connect to remote mysql server)
  mysql_db: 
    name: "{{ item }}" 
    state: present
    encoding: utf8
    login_host: "{{ seafile_login_host }}"
    login_user: "{{ seafile_login_user }}"
    login_password: "{{ seafile_login_user_password }}"
  with_items: 
  - "{{ seafile_database_prefix }}ccnet"
  - "{{ seafile_database_prefix }}seafile"
  - "{{ seafile_database_prefix }}seahub" 
  register: __seafile_database_create
  when: seafile_create_database and not seafile_delegate_to_login_host


- name: import initial dump
  mysql_db: 
    name: "{{ seafile_database_prefix }}seahub"
    state: import
    login_host: "{{ seafile_mysql_host }}"
    login_user: "{{ seafile_mysql_user }}"
    login_password: "{{ seafile_mysql_password }}"
    target: "/{{ seafile_installation_path }}/seahub/sql/mysql.sql"
  when: __seafile_database_create.changed or seafile_init_database
