
- name: check installed version
  stat:
    path: "{{ seafile_installation_path }}"
  register: _seafile_installed

- name: Download Apt signing key
  get_url:
    url: https://linux-clients.seafile.com/seafile.asc
    dest: /usr/share/keyrings/seafile-keyring.asc

- name: Add Seafile repo to Apt source list
  copy:
    content: 'deb [arch=amd64 signed-by=/usr/share/keyrings/seafile-keyring.asc] https://linux-clients.seafile.com/seafile-deb/jammy/ stable main'
    dest: /etc/apt/sources.list.d/seafile.list

- name: Install Seafile
  apt:
    name: seafile-gui
    update_cache: yes

- name: link seafile to current
  file:
    src: "{{ seafile_installation_path }}"
    path: "{{ seafile_installation_link }}"
    state: link

    
